---
title: "datasets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
library(stringr)
```

## 内置数据集 datasets

`datasets`包是默认载入的，故而其数据集可直接通过调用名字。


```{r datasets}

library(tidyverse)
library(magrittr)
library(stringr)

data_class <- data(package = "datasets") %>%
  use_series(result) %>%
  as_tibble() %>%
  # select(Item, Title) %>%
  use_series(Item) %>% 
  str_replace_all(" (.*)", "") %>%
  mget(envir = as.environment("package:datasets")) %>%
  map(class)

m_name <- unique(names(data_class))

m_class <- unique(unlist(data_class))

t1 <- data_class %>% map(match, m_class) %>% unlist()

data_class %>% map(length) %>% 

for(n in 1:104) {
  i <- n
  j <- match(data_class[[n]], m_class)
  if(length(i) != length(j)) i <- rep(i, length(j))
  # print(i)
  # print(j)
  if(n == 1) {
    x <- i
    y <- j
    } else {
      x <- c(x, i)
      y <- c(y, j)
    }
}

(D <- sparseMatrix(i = x, j = y, x = 1, dimnames = list(m_name, m_class)))
summary(D)
str(D) # note that *internally* 0-based row indices are used

```

### 向量

```{r vector}
LETTERS    #26个大写字母
letters    #26个小写字母
month.abb    #12个月份的三字母缩写
month.name    #12个月份的全称
pi    #3.14...
```

